services:
  frontend:
    image: "ishan1607/frontend:s2"
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - ishan

  backend:
    image: "ishan1607/markdowneditor:s2"
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZ2VuLWxhbmctY2xpZW50LTA2MTUwNTE1NDQiLAogICJwcml2YXRlX2tleV9pZCI6ICJjZTVmM2Q5MjViNjZmYjUyNTIxNTZmMDVhYTViZTc2NzQ4ZWYzMzQxIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUMvcVVLU0dMSnRpZEo4XG5wSDJjRndYRUZUWFAwOHhkVFZsOUE0dFlvNTZ2bVFNZW1UTDBMM2RKOWJ0Z1NxL1Z5dlluSFpMS21vRTZmN0hqXG5MQXFrQzBiTlQyNmNRYTNrMlIrRnpDTElFcldXbGJiOUNGWG82aTc1dW1MQzFQOU1DRE9rK2tkcURtZTBuM2N3XG5tUG5YWTlRZkxkTEFtdzFselRYRDkwOGlOd1dNcWxIUi9PVENkMGM4OFZtOWtmdWx0Q2FZUDh1Y3EvbUF5eVVDXG51c1lpaGdBQVNvbEpET2dKc0Q4ekhEbjEwcDZWK0lteDg1cVgyakdtZE15RHJ3WmRxYUpQVExZRXcrTjR5VTY4XG5UUEh6YUtCT01kWEExcjRhVFFnVG5LR08vUmpvMVZmbDhYa2xOcGRIMEU0NDVxZnFtYjBxL08zRXZZOHkybHQrXG5INDBqYjgxREFnTUJBQUVDZ2dFQUdhMUhhZU05SkVldWwxeENKOE05MW9NdzdtTGxvaXBXcnRUbXVqMVJhUjBLXG51ZkswVE5wL0ZMMkRHT2RvbnkvTnduZkh6clRjVTBZQVF2c0hnZXF3MVppcXJPeHZxNVViRUFYRk15Q3Vpem9MXG5oZUt6Lzd4QUJ0emRsbFNLejFqWjhtUkZaUVFCQ01YRVpoSllobTZ0WUcvM0tDNmRvT0haTGlQWHlqR3M0S2RGXG5NUVp2ckV2QVhNUUVON1RpcXIwVWxqSUJ3VnJ4UFAzaGsyMzY1Y2Z2NUxRQmJWWTZ1emZ5K3JNQ2lIWjFqQ0hzXG5VQk1aTjJyRi9Kd3pjWEVGOVJUZmdqVGI0bTJMK3UyVnRKb0psUkxJSVUzOGc2dkMzSmh1RnUwcWIxUzBWcjB0XG5aQXRRbjNHTXZwWFZlQnFJUkNUaktTVXF0TWE4Y3VNWFkyM0lDdS9qd1FLQmdRRHlFWmVvZ0F6clBodmJNNEdvXG5qNUd6L1B3RWl4dVhST25ZdXhjbnFKLzRCTmNJSFJFTDhzdm9ac1lySG9NWmgrU0NwM2FETGFLN2JSaWpOSy9zXG5ZbzJJbWR1d1ZaZ1VxQzNCM1RUN29TU2J2Q3RXdmlKRFlVMCsxOUtrQWlST2RldllvQ1BpdlVXVXo1RDM4aDRWXG5nSDJPaE5zS3B6UUNSVFhPd1JhOEVNaFZDUUtCZ1FES3NRTGxwQ3JIQzZidVJ4WTBFdjR5SWNkV0V2RjF0bnVGXG4yeS80M3REOU85VkxRQTNSalBWclhUOWxaUm9wYlFlSkJoTHI5S2U3L0dxQlVMdDVjRDAwclVSSzNhb0w2aHFLXG5XOGIxVERDOU1PMjN3cXIxWjlpakhWN2l0Z3Ezc0JrVDhFc3RYQms5dHBHUEJLZXIvcWxTdnAxbXU0Ynk3bHNmXG51OVdEOWRsTzZ3S0JnUURUMFdjV3orMytEeHdMQkpnSmFvL0JvcmJZTnUyT3dZT3EzWk9XWld5TmQ1YStCOGs1XG4zbHhsWVVFNHkvdEY1TzZsRVdxWHdPQXNCM3ZPbkRUd3NSQk9IdXZvOGcwZ3prVXo1YUFPSytTL3pibFNydytHXG5UR2R1ZlNaWjAzSDNvaUlkTFl3WlJTdlUyb2h0SGxVSzFhT0lpV0t1Z0w3MjJaOEs2MVU4ZmFiL0dRS0JnUUNtXG5FUmRkalA3YmJDbU42a0kvMGh2Z2VScDM1RGRmQ1c3MUFkdXhIT1cveFFrQmlXNkk5T09TM3FoMWE3dGVtNHpqXG44RTBLYzc0RjRFNW11djJQQnEydS9oTUkvOG8xenMyRjlLSHpFa1NRallrRzJRRDI1ZWx4NHp0OXBrYnJydVV0XG5GK0NRUG5nVHZ3Uk5XRFFFVURic3EyNE00TEkxVWFMcFFoMHk2L2ZxbHdLQmdBMnRYRW1zU1JtTDlJTDU4cDFaXG4yY1ZNUldJYjl6U0J4Wm5TRWlRN1d2MFBGOVk1eUpDa051MlU2Q2d3bFhFMllkcnljQW1Kak50T0RCVytmSC9iXG5EZHVIUVRzWFlldnpTanlIbnVhRkZEMHFSWklJaW1qRW1aZnkzYUFVVW9oQXdNVmdFNGxzKzFNbXg4NWl5S00rXG5zUmI0Z3BSVjAzeVdwV0VmT09PeElBM0Zcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJnZHJpdmUtYXBpLWtleUBnZW4tbGFuZy1jbGllbnQtMDYxNTA1MTU0NC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDU1Mjc0NDE2MjU4MDk3NTc0OTMiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2dkcml2ZS1hcGkta2V5JTQwZ2VuLWxhbmctY2xpZW50LTA2MTUwNTE1NDQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
      - JAVA_OPTS=-Xms512m -Xmx2048m
    networks:
      - ishan

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ishan
    depends_on:
      - frontend
      - backend

networks:
  ishan:
    driver: "bridge"